[building_form]
"硬山" = "hard_hill"
"悬山" = "hanging_hill"
"歇山" = "hip_roof"
"庑殿" = "hip_roof_palace"
"攒尖" = "pyramidal_roof"

# 继承
[building_form."四檩卷棚小式"]
inherit = [
    "roof_types.roll_shed",
    "construction_grades.small_style",
    "structural_modules.column_diameter_system",
]
purlin_count = 4
description = "四檩卷棚小式房屋，常见于园林小亭或廊屋。"


[building_form."五檩歇山大式"]
inherit = [
    "roof_types.xie_shan",
    "construction_grades.large_style",
    "structural_modules.column_diameter_system",
]
purlin_count = 5
description = "五檩歇山大式建筑，为中式厅堂常见构架。"

[building_form."六檩卷棚大式"]
inherit = [
    "roof_types.xie_shan",
    "construction_grades.large_style",
    "structural_modules.column_diameter_system",
]
purlin_count = 5
description = "测试柳林卷棚大式。"
