[house_config]

[house_config.main]
description = "正房"
inherit = ["construction_grades.large_style"]
orientation = "south"


[house_config.wing]
description = "厢房"
inherit = ["construction_grades.small_style"]
orientation = "east_west"


[house_config.reverse]
description = "倒座房"
inherit = ["construction_grades.small_style"]
orientation = "north"

