# 建筑形式
[house_forms]

hard_hill = "硬山"
hanging_hill = "悬山"
hip_roof = "歇山"
hip_roof_palace = "庑殿"
pyramidal_roof = "攒尖"


["四檩卷棚小式"]
construction_grade = "small_style"
roof_type = "roll_shed"
modular_system = "doukou_style"
has_dougong = false
has_flying_rafters = false
description = "四檩卷棚小式房屋"

["六檩硬山大式"]
construction_grade = "large_style"
roof_type = "hard_hill"
modular_system = "doukou_style"
has_dougong = true
has_flying_rafters = true
description = "六檩硬山大式房屋"
